# Generated by Django 5.1.2 on 2024-11-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notable_work', models.TextField(blank=True, null=True)),
                ('about', models.TextField()),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('born', models.CharField(blank=True, max_length=50, null=True)),
                ('died', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('known_for', models.CharField(blank=True, max_length=255, null=True)),
                ('designed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('developer', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowl.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowl.type')),
            ],
            options={
                'db_table': 'articles',
                'managed': True,
            },
        ),
    ]
