# -*- coding: utf-8 -*-
"""cloning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTxDl02gNRoqKtq3W5Dp1RmcS7c1mzk8
"""

import subprocess

def clone_repository(repo_url, destination_folder):
    try:
        subprocess.run(["git", "clone", repo_url, destination_folder], check=True)
        print(f"Repository cloned into {destination_folder}")
    except subprocess.CalledProcessError as e:
        print(f"Error occurred: {e}")

repo_url = "https://github.com/twelvewizards/knowlbase.git"
destination_folder = "./cloned_repo"
clone_repository(repo_url, destination_folder)

pip install gitpython

from git import Repo

def clone_repository(repo_url, destination_folder):
    try:
        Repo.clone_from(repo_url, destination_folder)
        print(f"Repository cloned into {destination_folder}")
    except Exception as e:
        print(f"Error occurred: {e}")

repo_url = "https://github.com/twelvewizards/knowlbase.git"
destination_folder = "./cloned_repo"
clone_repository(repo_url, destination_folder)





